### ISSUE TITLE
unable to load midje in repl

### ISSUE THREAD

**Issue by bfabry** [marick/specter-book-code#1]
Pretty weird. Whole session:

```
nREPL server started on port 62603 on host 127.0.0.1 - nrepl://127.0.0.1:62603
(use 'com.rpl.specter)
WARNING: update already refers to: #'clojure.core/update in namespace: com.rpl.specter, being replaced by: #'com.rpl.specter/update
WARNING: update already refers to: #'clojure.core/update in namespace: user, being replaced by: #'com.rpl.specter/update
=> nil
(select [:a] {:a 1})
=> [1]
(select [:a :b] {:a {:b 1}})
=> [1]
(select [:a] {})
=> [nil]
(select [:a] {:not-a 1})
=> [nil]
(select [:a :b] {:a {}})
=> [nil]
(select [:a] nil)
=> [nil]
(select [:a] :something-random)
=> [nil]
(select [:a :b] {:a 1})
=> [nil]
(use 'midje.repl)
clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: No such var: specter/transform, compiling:(such/readable.clj:184:3)
             java.lang.RuntimeException: No such var: specter/transform
(autotest)
clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: Unable to resolve symbol: autotest in this context, compiling:(/Users/bfabry/Library/Caches/IdeaIC15/tmp/form-init5362378062424459758.clj:1:1)
             java.lang.RuntimeException: Unable to resolve symbol: autotest in this context
(use 'midje.repl)
clojure.lang.Compiler$CompilerException: java.lang.Exception: namespace 'commons.clojure.core' not found, compiling:(midje/repl.clj:1:1)
                    java.lang.Exception: namespace 'commons.clojure.core' not found
(use 'midje.repl)
clojure.lang.Compiler$CompilerException: java.lang.Exception: namespace 'commons.clojure.core' not found, compiling:(midje/repl.clj:1:1)
                    java.lang.Exception: namespace 'commons.clojure.core' not found
```

**Comment by bfabry** [comment]
Ahhhh due to weirdness in my profiles.clj, I suspect primarily because I had a newer version of specter as a dependency.

**Comment by marick** [comment]
You had a newer version? The book files seem to be using the most recent version.

**Comment by bfabry** [comment]
err, s/new/old old old/

**Comment by bcambel** [comment]
I have the exact same exception happening right now, I am currently using 0.11.0. The exception only happens when the `clojure.tools.namespace.repl/refresh` method runs. Anybody has any idea? 

```
Exception in thread "main" java.lang.RuntimeException: No such var: specter/transform, compiling:(such/readable.clj:184:3)
    at clojure.lang.Compiler.analyze(Compiler.java:6688)
    at clojure.lang.Compiler.analyze(Compiler.java:6625)
    at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3766)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6870)
    at clojure.lang.Compiler.analyze(Compiler.java:6669)
    at clojure.lang.Compiler.analyze(Compiler.java:6625)
    at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6001)
    at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5380)
    at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3972)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6866)
    at clojure.lang.Compiler.analyze(Compiler.java:6669)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6856)
    at clojure.lang.Compiler.analyze(Compiler.java:6669)
    at clojure.lang.Compiler.access$300(Compiler.java:38)
    at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:589)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)
    at clojure.lang.Compiler.analyze(Compiler.java:6669)
    at clojure.lang.Compiler.analyze(Compiler.java:6625)
    at clojure.lang.Compiler.eval(Compiler.java:6931)
    at clojure.lang.Compiler.eval(Compiler.java:6916)
    at clojure.lang.Compiler.load(Compiler.java:7379)
    at clojure.lang.RT.loadResourceScript(RT.java:372)
    at clojure.lang.RT.loadResourceScript(RT.java:363)
    at clojure.lang.RT.load(RT.java:453)
    at clojure.lang.RT.load(RT.java:419)
    at clojure.core$load$fn__5677.invoke(core.clj:5893)
    at clojure.core$load.invokeStatic(core.clj:5892)
    at clojure.core$load.doInvoke(core.clj:5876)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invokeStatic(core.clj:5697)
    at clojure.core$load_one.invoke(core.clj:5692)
    at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
    at clojure.core$load_lib.invokeStatic(core.clj:5736)
    at clojure.core$load_lib.doInvoke(core.clj:5717)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invokeStatic(core.clj:648)
    at clojure.core$load_libs.invokeStatic(core.clj:5774)
    at clojure.core$load_libs.doInvoke(core.clj:5758)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invokeStatic(core.clj:648)
    at clojure.core$require.invokeStatic(core.clj:5796)
    at clojure.core$require.doInvoke(core.clj:5796)
    at clojure.lang.RestFn.invoke(RestFn.java:436)
    at such.imperfection$eval40348$loading__5569__auto____40349.invoke(imperfection.clj:1)
    at such.imperfection$eval40348.invokeStatic(imperfection.clj:1)
    at such.imperfection$eval40348.invoke(imperfection.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6927)
    at clojure.lang.Compiler.eval(Compiler.java:6916)
    at clojure.lang.Compiler.load(Compiler.java:7379)
    at clojure.lang.RT.loadResourceScript(RT.java:372)
    at clojure.lang.RT.loadResourceScript(RT.java:363)
    at clojure.lang.RT.load(RT.java:453)
    at clojure.lang.RT.load(RT.java:419)
    at clojure.core$load$fn__5677.invoke(core.clj:5893)
    at clojure.core$load.invokeStatic(core.clj:5892)
    at clojure.core$load.doInvoke(core.clj:5876)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invokeStatic(core.clj:5697)
    at clojure.core$load_one.invoke(core.clj:5692)
    at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
    at clojure.core$load_lib.invokeStatic(core.clj:5736)
    at clojure.core$load_lib.doInvoke(core.clj:5717)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invokeStatic(core.clj:648)
    at clojure.core$load_libs.invokeStatic(core.clj:5774)
    at clojure.core$load_libs.doInvoke(core.clj:5758)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invokeStatic(core.clj:648)
    at clojure.core$require.invokeStatic(core.clj:5796)
    at clojure.core$require.doInvoke(core.clj:5796)
    at clojure.lang.RestFn.invoke(RestFn.java:2422)
    at commons.clojure.core$eval39761$loading__5569__auto____39762.invoke(core.clj:1)
    at commons.clojure.core$eval39761.invokeStatic(core.clj:1)
    at commons.clojure.core$eval39761.invoke(core.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6927)
    at clojure.lang.Compiler.eval(Compiler.java:6916)
    at clojure.lang.Compiler.load(Compiler.java:7379)
    at clojure.lang.RT.loadResourceScript(RT.java:372)
    at clojure.lang.RT.loadResourceScript(RT.java:363)
    at clojure.lang.RT.load(RT.java:453)
    at clojure.lang.RT.load(RT.java:419)
    at clojure.core$load$fn__5677.invoke(core.clj:5893)
    at clojure.core$load.invokeStatic(core.clj:5892)
    at clojure.core$load.doInvoke(core.clj:5876)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invokeStatic(core.clj:5697)
    at clojure.core$load_one.invoke(core.clj:5692)
    at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
    at clojure.core$load_lib.invokeStatic(core.clj:5736)
    at clojure.core$load_lib.doInvoke(core.clj:5717)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invokeStatic(core.clj:648)
    at clojure.core$load_libs.invokeStatic(core.clj:5774)
    at clojure.core$load_libs.doInvoke(core.clj:5758)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invokeStatic(core.clj:650)
    at clojure.core$use.invokeStatic(core.clj:5860)
    at clojure.core$use.doInvoke(core.clj:5860)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at midje.emission.levels$eval39753$loading__5569__auto____39754.invoke(levels.clj:1)
    at midje.emission.levels$eval39753.invokeStatic(levels.clj:1)
    at midje.emission.levels$eval39753.invoke(levels.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6927)
    at clojure.lang.Compiler.eval(Compiler.java:6916)
    at clojure.lang.Compiler.load(Compiler.java:7379)
    at clojure.lang.RT.loadResourceScript(RT.java:372)
    at clojure.lang.RT.loadResourceScript(RT.java:363)
    at clojure.lang.RT.load(RT.java:453)
    at clojure.lang.RT.load(RT.java:419)
    at clojure.core$load$fn__5677.invoke(core.clj:5893)
    at clojure.core$load.invokeStatic(core.clj:5892)
    at clojure.core$load.doInvoke(core.clj:5876)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invokeStatic(core.clj:5697)
    at clojure.core$load_one.invoke(core.clj:5692)
    at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
    at clojure.core$load_lib.invokeStatic(core.clj:5736)
    at clojure.core$load_lib.doInvoke(core.clj:5717)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invokeStatic(core.clj:648)
    at clojure.core$load_libs.invokeStatic(core.clj:5774)
    at clojure.core$load_libs.doInvoke(core.clj:5758)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invokeStatic(core.clj:648)
    at clojure.core$require.invokeStatic(core.clj:5796)
    at clojure.core$require.doInvoke(core.clj:5796)
    at clojure.lang.RestFn.invoke(RestFn.java:512)
    at midje.config$eval39668$loading__5569__auto____39669.invoke(config.clj:1)
    at midje.config$eval39668.invokeStatic(config.clj:1)
    at midje.config$eval39668.invoke(config.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6927)
    at clojure.lang.Compiler.eval(Compiler.java:6916)
    at clojure.lang.Compiler.load(Compiler.java:7379)
    at clojure.lang.RT.loadResourceScript(RT.java:372)
    at clojure.lang.RT.loadResourceScript(RT.java:363)
    at clojure.lang.RT.load(RT.java:453)
    at clojure.lang.RT.load(RT.java:419)
    at clojure.core$load$fn__5677.invoke(core.clj:5893)
    at clojure.core$load.invokeStatic(core.clj:5892)
    at clojure.core$load.doInvoke(core.clj:5876)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invokeStatic(core.clj:5697)
    at clojure.core$load_one.invoke(core.clj:5692)
    at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
    at clojure.core$load_lib.invokeStatic(core.clj:5736)
    at clojure.core$load_lib.doInvoke(core.clj:5717)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invokeStatic(core.clj:648)
    at clojure.core$load_libs.invokeStatic(core.clj:5774)
    at clojure.core$load_libs.doInvoke(core.clj:5758)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invokeStatic(core.clj:648)
    at clojure.core$require.invokeStatic(core.clj:5796)
    at clojure.core$require.doInvoke(core.clj:5796)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at user$eval39662.invokeStatic(form-init1497253124456077418.clj:1)
    at user$eval39662.invoke(form-init1497253124456077418.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6927)
    at clojure.lang.Compiler.eval(Compiler.java:6916)
    at clojure.lang.Compiler.eval(Compiler.java:6916)
    at clojure.lang.Compiler.load(Compiler.java:7379)
    at clojure.lang.Compiler.loadFile(Compiler.java:7317)
    at clojure.main$load_script.invokeStatic(main.clj:275)
    at clojure.main$init_opt.invokeStatic(main.clj:277)
    at clojure.main$init_opt.invoke(main.clj:277)
    at clojure.main$initialize.invokeStatic(main.clj:308)
    at clojure.main$null_opt.invokeStatic(main.clj:342)
    at clojure.main$null_opt.invoke(main.clj:339)
    at clojure.main$main.invokeStatic(main.clj:421)
    at clojure.main$main.doInvoke(main.clj:384)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:383)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: No such var: specter/transform
    at clojure.lang.Util.runtimeException(Util.java:221)
    at clojure.lang.Compiler.resolveIn(Compiler.java:7138)
    at clojure.lang.Compiler.resolve(Compiler.java:7108)
    at clojure.lang.Compiler.analyzeSymbol(Compiler.java:7069)
    at clojure.lang.Compiler.analyze(Compiler.java:6648)
    ... 174 more
```

**Comment by marick** [comment]
Sorry for the delay - I was in Europe. The problem was that the API changed between Specter 0.9 and 0.11. Because Midje used Specter 0.9, hilarity ensued. I've fixed Midje (1.9.0-alpha2), and will now go and fix the book code and text.

**Comment by marick** [comment]
Note that the core Specter functions (like `update` and `transform`) are now in `com.rpl.specter.macros`.

**Comment by marick** [comment]
The code in this repo now uses the latest Midje, etc. The code that uses Specter has been changed to match the new namespace structure.
